name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        go-version:
          - 1.18.10
          - 1.19.10
          - 1.20.5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - run: go test -v ./...
