name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        go-version:
          - 1.20.14
          - 1.21.12
          - 1.22.5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - run: go test -v ./...
